export const Users =[
  
  {
    id:1,
    profilePicture:"Assets/Persons/1.jpeg",
    username:"Naruto Uzumaki",
  },
  {
    id:2,
    profilePicture:"Assets/Persons/2.jpeg",
    username:"Midoriya",
  },
  {
    id:3,
    profilePicture:"Assets/Persons/3.jpeg",
    username:"Tanjiro",
  },
  {
    id:4,
    profilePicture:"Assets/Persons/4.jpeg",
    username:"Mitsuri",
  },
  {
    id:5,
    profilePicture:"Assets/Persons/5.jpeg",
    username:"Killua",
  },
  {
    id:6,
    profilePicture:"Assets/Persons/6.jpeg",
    username:"Gojo Sattoru",
  },
  {
    id:7,
    profilePicture:"Assets/Persons/7.jpeg",
    username:"Saitama",
  },
  {
    id:8,
    profilePicture:"Assets/Persons/8.jpeg",
    username:"Annya",
  },
  {
    id:9,
    profilePicture:"Assets/Persons/9.jpeg",
    username:"Luffy",
  },
  {
    id:10,
    profilePicture:"Assets/Persons/10.jpeg",
    username:"Kaguya",
  },
];

export const Posts =[
  {
   id: 1,
   desc: "hi",
   date:"5 mins ago",
   photo: "Assets/Posts/1.jpeg",   
   userId: 1,
   like: 34,
   comment: 10,
  },
  {
    id: 2,
    desc: "hi",
    date:"5 mins ago",
    photo: "Assets/Posts/2.jpeg",   
    userId: 2,
    like: 36,
    comment: 12,
   },
   {
    id: 3,
    desc: "hi",
    date:"5 mins ago",
    photo: "Assets/Posts/3.jpeg",   
    userId: 3,
    like: 38,
    comment: 14,
   },
   {
    id: 4,
    desc: "hi",
    date:"5 mins ago",
    photo: "Assets/Posts/4.jpeg",   
    userId: 4,
    like: 40,
    comment: 16,
   },
   {
    id: 5,
    desc: "hi",
    date:"5 mins ago",
    photo: "Assets/Posts/5.jpeg",   
    userId: 5,
    like: 42,
    comment: 18,
   },
   {
    id: 6,
    desc: "hi",
    date:"5 mins ago",
    photo: "Assets/Posts/6.jpeg",   
    userId: 6,
    like: 44,
    comment: 20,
   },
   {
    id: 7,
    desc: "hi",
    date:"5 mins ago",
    photo: "Assets/Posts/7.jpeg",   
    userId: 7,
    like: 46,
    comment: 22,
   },
   {
    id: 8,
    desc: "hi",
    date:"5 mins ago",
    photo: "Assets/Posts/8.jpeg",   
    userId: 8,
    like: 48,
    comment: 24,
   },
   {
    id: 9,
    desc: "hi",
    date:"5 mins ago",
    photo: "Assets/Posts/9.jpeg",   
    userId: 9,
    like: 50,
    comment: 26,
   },
   {
    id: 10,
    desc: "hi",
    date:"5 mins ago",
    photo: "Assets/Posts/10.jpeg",   
    userId: 10,
    like: 52,
    comment: 28,
   },
]